CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type INTEGER NOT NULL CHECK (type IN (1, 2)),
  place TEXT NOT NULL,
  date DATE,
  count INTEGER,
  status INTEGER NOT NULL CHECK (status IN (1, 2, 3, 4, 5)),
  image TEXT,
  last_date DATE,
  cycle INTEGER,
  threshold INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS items_status_idx ON items (status);
CREATE INDEX IF NOT EXISTS items_type_date_idx ON items (type, date);

